/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-10-01 08:08:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class outer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1633064368758L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1633074893182L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no\" />\r\n");
      out.write("    <title>You are a pretty girl</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.14.0/css/all.css\" integrity=\"sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/default.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/auto_slide.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/header.css\" />\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"./js/header.js\" defer> </script>\r\n");
      out.write("    <script src=\"./js/auto_slide.js\" defer> </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("  <div>\r\n");
      out.write("    <ul class=\"hdGnb\">\r\n");
      out.write("      <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("      <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("      <li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("      <li><a href=\"#\">마이쇼핑</a></li>\r\n");
      out.write("      <li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"navbar\">\r\n");
      out.write("    <div class=\"navbar_logo\">\r\n");
      out.write("      <i class=\"fas fa-socks\"></i>\r\n");
      out.write("      <a href=\"\">DoDo Girls</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"navbar_menu\">\r\n");
      out.write("      <li><a href=\"#\">HOME</a></li>\r\n");
      out.write("      <li><a href=\"#\">NEW10%</a></li>\r\n");
      out.write("      <li><a href=\"#\">BEST</a></li>\r\n");
      out.write("      <li><a href=\"outer.jsp\">OUTER</a></li>\r\n");
      out.write("      <li><a href=\"#\">TOP</a></li>\r\n");
      out.write("      <li><a href=\"#\">BLOUSE</a></li>\r\n");
      out.write("      <li><a href=\"#\">SKIRT</a></li>\r\n");
      out.write("      <li><a href=\"#\">PANTS</a></li>\r\n");
      out.write("      <li><a href=\"#\">CONTACT US</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"#\" class=\"navbar_toogleBtn\">\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!--Main -->\r\n");
      out.write("      <h1 class=\"main_text\">OUTER BEST ITEM</h1>\r\n");
      out.write("      <div class=\"table-wrap\">\r\n");
      out.write("          <div class=\"item1\">\r\n");
      out.write("              <img src=\"images/p-images/outer1.jpg\"/>\r\n");
      out.write("              <p>밀러스 더블 정장 자켓</p>\r\n");
      out.write("              <p>39,900원</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item2\">\r\n");
      out.write("              <img src=\"images/p-images/outer2.gif\"/>\r\n");
      out.write("              <p>몬드 셔츠 배색 가디건</p>\r\n");
      out.write("              <p>35,900원</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item3\">\r\n");
      out.write("              <img src=\"images/p-images/outer3.gif\"/>\r\n");
      out.write("              <p>콤비제인 스판 자켓</p>\r\n");
      out.write("              <p>59,900원</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item4\">\r\n");
      out.write("              <img src=\"images/p-images/outer4.gif\"/>\r\n");
      out.write("              <p>코코 수술 트위드자켓</p>\r\n");
      out.write("              <p>99,900원</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item5\">\r\n");
      out.write("              <img src=\"images/p-images/outer5.gif\"/>\r\n");
      out.write("              <p>레보 스카프 자켓 반바지세트</p>\r\n");
      out.write("              <p>99,900원</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item6\">\r\n");
      out.write("              <img src=\"images/p-images/outer6.gif\"/>\r\n");
      out.write("              <p>빌리 배색체크 자켓 정장세</p>\r\n");
      out.write("              <p>99,900원</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item7\">\r\n");
      out.write("            <img src=\"images/p-images/outer7.gif\"/>\r\n");
      out.write("            <p>레베 클래식 롱 울 가디건</p>\r\n");
      out.write("            <p>39,900원</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item8\">\r\n");
      out.write("            <img src=\"images/p-images/outer8.gif\"/>\r\n");
      out.write("            <p>모어 트위드 자켓</p>\r\n");
      out.write("            <p>89,900원</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item8\">\r\n");
      out.write("            <img src=\"images/p-images/outer9.gif\"/>\r\n");
      out.write("            <p>핀 스트라이프 프릴 자켓</p>\r\n");
      out.write("            <p>116,100원</p>\r\n");
      out.write("        </div>\r\n");
      out.write("       </div>     \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("      <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer_info\"> \r\n");
      out.write("          <h3>(주)Fashion Mail</h3>\r\n");
      out.write("          <div>이용약관 | 개인정보처리방법</div>\r\n");
      out.write("          <div>대표:홍길동 사업자 등록번호. 000-000-000000 통신판매업신고번호. 제 2020-전주-0000호</div>\r\n");
      out.write("          <div>주소. 전라북도 전주시 ㅇㅇㅇㅇ 123</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"footer_info_cscenter\"> \r\n");
      out.write("          <h3>CS CENTER</h3>\r\n");
      out.write("          <div>02 1234 5678</div>\r\n");
      out.write("          <div>WORK TIME</div>\r\n");
      out.write("          <div>10:00-18:00(토/일 공휴일 휴무)</div>\r\n");
      out.write("          <div>12:00-13:00 점심시간</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <dev class=\"footer_info_refund\"> \r\n");
      out.write("          <h3>교환/반품</h3>\r\n");
      out.write("          <div>자주하는 질문</div>\r\n");
      out.write("          <div>E-MAIL </div>\r\n");
      out.write("          <div>abcdefe@gmail.com</div>\r\n");
      out.write("        </div>         \r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
